import 'package:student_portal/app/base/base_controller.dart';
import 'package:student_portal/app/modules/progress/models/progress.dart';

class ProgressController extends BaseController {
  final progress = Progress(subjects: [
    Subject(
      name: "Deep Learning",
      credit: 3,
      day: [
        Day(isPresent: true, homeWork: 40),
        Day(isPresent: true, homeWork: 75.5),
        Day(isPresent: true, homeWork: 0),
        Day(isPresent: true, homeWork: 55),
        Day(isPresent: false, homeWork: 0),
        Day(isPresent: true, homeWork: 100),
        Day(isPresent: true, homeWork: 98),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
      ],
      midSemester: 50.2,
      endSemester: 75,
      score: 3.4,
      grade: "B",
      isFailed: false,
    ),Subject(
      name: "Software Testing",
      credit: 3,
      day: [
        Day(isPresent: true, homeWork: 75.5),
        Day(isPresent: false, homeWork: 0),
        Day(isPresent: true, homeWork: 10),
        Day(isPresent: false, homeWork: 0),
        Day(isPresent: false, homeWork: 0),
        Day(isPresent: true, homeWork: 75.5),
        Day(isPresent: false, homeWork: 0),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
      ],
      midSemester: 50.2,
      endSemester: 75,
      score: 0,
      grade: "E",
      isFailed: true,
    ),
    Subject(
      name: "Advance Web Programming",
      credit: 3,
      day: [
        Day(isPresent: true, homeWork: 25),
        Day(isPresent: true, homeWork: 40),
        Day(isPresent: true, homeWork: 65),
        Day(isPresent: true, homeWork: 75),
        Day(isPresent: true, homeWork: 90),
        Day(isPresent: true, homeWork: 100),
        Day(isPresent: true, homeWork: 56),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
      ],
      midSemester: 50.2,
      endSemester: 75,
      score: 3.4,
      grade: "B",
      isFailed: false,
    ),
    Subject(
      name: "Research Methods",
      credit: 3,
      day: [
        Day(isPresent: true, homeWork: null),
        Day(isPresent: true, homeWork: null),
        Day(isPresent: true, homeWork: null),
        Day(isPresent: true, homeWork: null),
        Day(isPresent: false, homeWork: 0),
        Day(isPresent: true, homeWork: null),
        Day(isPresent: true, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
        Day(isPresent: null, homeWork: null),
      ],
      midSemester: 50.2,
      endSemester: 75,
      score: 3.4,
      grade: "B",
      isFailed: false,
    ),
  ], score: 3.1, grade: "B");
}
